//
// Created by Luecx on 24.06.2021.
//

#ifndef ENGINE3D_SRC_CONFIG_H_
#define ENGINE3D_SRC_CONFIG_H_

#define MAX_DIRECTIONAL_LIGHTS (4)
#define MAX_POINT_LIGHTS (8)
#define MAX_SPOT_LIGHTS (4)
#define MAX_SHADOWS (8)
#define SHADOW_RESOLUTION (4096)

#endif // ENGINE3D_SRC_CONFIG_H_
